/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dotharaai/.choosenim/toolchains/nim-0.13.0/lib -o /home/dotharaai/projects/nim/abc158/nimcache/abc158_D.o /home/dotharaai/projects/nim/abc158/nimcache/abc158_D.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
typedef struct Doublylinkedlist105010 Doublylinkedlist105010;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Doublylinkednodeobj105016 Doublylinkednodeobj105016;
typedef struct TY105477 TY105477;
typedef struct TY15805 TY15805;
typedef struct Slice88482 Slice88482;
typedef struct Cell47905 Cell47905;
typedef struct TNimType TNimType;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50214 Gcstat50214;
typedef struct TNimNode TNimNode;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Doublylinkedlist105010  {
Doublylinkednodeobj105016* head;
Doublylinkednodeobj105016* tail;
};
struct  Slice88482  {
NI a;
NI b;
};
struct  Doublylinkednodeobj105016  {
Doublylinkednodeobj105016* next;
Doublylinkednodeobj105016* prev;
NimStringDesc* value;
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50214 stat;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
struct TY105477 {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY15805 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, initdoublylinkedlist_105005)(Doublylinkedlist105010* Result);
N_NIMCALL(void, append_105043)(Doublylinkedlist105010* L, NimStringDesc* value);
N_NIMCALL(Doublylinkednodeobj105016*, newdoublylinkednode_105053)(NimStringDesc* value);
N_NIMCALL(void, append_105069)(Doublylinkedlist105010* L, Doublylinkednodeobj105016* n);
N_NIMCALL(void, prepend_105244)(Doublylinkedlist105010* L, NimStringDesc* value);
N_NIMCALL(void, prepend_105262)(Doublylinkedlist105010* L, Doublylinkednodeobj105016* n);
N_NIMCALL(TY105477*, HEX40_105471)(NIM_CHAR* a, NI aLen0);
N_NIMCALL(TY15805*, newseq_105810)(NI len);
N_NIMCALL(TY15805*, reversed_105848)(NimStringDesc** a, NI aLen0);
N_NIMCALL(TY15805*, reversed_105864)(NimStringDesc** a, NI aLen0, NI first, NI last);
N_NIMCALL(NimStringDesc*, solve_105001)(void);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(NimStringDesc*, readline_15510)(FILE* f);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
static N_INLINE(Slice88482, HEX2EHEX2E_101424)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(TY15805*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nsuJoin)(NimStringDesc** a, NI aLen0);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47905*, usrtocell_51840)(void* usr);
static N_INLINE(void, rtladdzct_53401)(Cell47905* c);
N_NOINLINE(void, addzct_51817)(Cellseq47921* s, Cell47905* c);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, abc158_DInit000)(void);
NIM_EXTERNC N_NOINLINE(void, abc158_DDatInit000)(void);
STRING_LITERAL(TMP166, "len(a) == L string modified while iterating over it", 51);
STRING_LITERAL(TMP178, " ", 1);
STRING_LITERAL(TMP179, "1", 1);
STRING_LITERAL(TMP181, "", 0);
STRING_LITERAL(TMP185, "len(a) == L seq modified while iterating over it", 48);
extern TFrame* frameptr_19436;
extern Gcheap50218 gch_50259;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(Slice88482, HEX2EHEX2E_101424)(NI a, NI b) {
	Slice88482 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(270, "system.nim");
	result.a = a;
	nimln(271, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(Cell47905*, usrtocell_51840)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53401)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_51817((&gch_50259.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_51840(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_51840((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_53401(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NimStringDesc*, solve_105001)(void) {
	NimStringDesc* result_105003;
	Doublylinkedlist105010 s_105039;
	NI qnum;
	NimStringDesc* LOC9;
	NIM_BOOL lr;
	nimfr("solve", "abc158_D.nim")
{	result_105003 = 0;
	memset((void*)(&s_105039), 0, sizeof(s_105039));
	nimln(6, "abc158_D.nim");
	chckNil((void*)(&s_105039));
	memset((void*)(&s_105039), 0, sizeof(s_105039));
	initdoublylinkedlist_105005((&s_105039));
	{
		NIM_CHAR c_105041;
		NimStringDesc* HEX3Atmp_106032;
		NI i_106035;
		NI L_106037;
		c_105041 = 0;
		HEX3Atmp_106032 = 0;
		nimln(7, "abc158_D.nim");
		HEX3Atmp_106032 = readline_15510(stdin);
		nimln(3379, "system.nim");
		i_106035 = ((NI) 0);
		nimln(3380, "system.nim");
		L_106037 = (HEX3Atmp_106032 ? HEX3Atmp_106032->Sup.len : 0);
		{
			nimln(3381, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				NI TMP165;
				if (!(i_106035 < L_106037)) goto LA3;
				nimln(3382, "system.nim");
				if ((NU)(i_106035) > (NU)(HEX3Atmp_106032->Sup.len)) raiseIndexError();
				c_105041 = HEX3Atmp_106032->data[i_106035];
				nimln(8, "abc158_D.nim");
				LOC4 = 0;
				LOC4 = nimCharToStr(c_105041);
				append_105043((&s_105039), LOC4);
				nimln(3383, "system.nim");
				TMP165 = addInt(i_106035, ((NI) 1));
				i_106035 = (NI)(TMP165);
				nimln(3384, "system.nim");
				{
					if (!!(((HEX3Atmp_106032 ? HEX3Atmp_106032->Sup.len : 0) == L_106037))) goto LA7;
					failedassertimpl_89116(((NimStringDesc*) &TMP166));
				}
				LA7: ;
			} LA3: ;
		}
	}
	nimln(10, "abc158_D.nim");
	LOC9 = 0;
	LOC9 = readline_15510(stdin);
	qnum = nsuParseInt(LOC9);
	nimln(11, "abc158_D.nim");
	lr = NIM_TRUE;
	{
		NI i_105241;
		Slice88482 HEX3Atmp_106039;
		i_105241 = 0;
		memset((void*)(&HEX3Atmp_106039), 0, sizeof(HEX3Atmp_106039));
		nimln(3548, "system.nim");
		nimln(3550, "system.nim");
		HEX3Atmp_106039 = HEX2EHEX2E_101424(((NI) 0), subInt(qnum, 1));
		{
			NI x_106043;
			NI HEX3Atmp_106045;
			NI HEX3Atmp_106047;
			NI res_106049;
			x_106043 = 0;
			HEX3Atmp_106045 = 0;
			HEX3Atmp_106047 = 0;
			nimln(2026, "system.nim");
			HEX3Atmp_106045 = HEX3Atmp_106039.a;
			HEX3Atmp_106047 = HEX3Atmp_106039.b;
			nimln(1874, "system.nim");
			res_106049 = HEX3Atmp_106045;
			{
				nimln(1875, "system.nim");
				while (1) {
					TY15805* query;
					NimStringDesc* LOC14;
					NI TMP180;
					if (!(res_106049 <= HEX3Atmp_106047)) goto LA13;
					nimln(1876, "system.nim");
					x_106043 = res_106049;
					nimln(2026, "system.nim");
					i_105241 = x_106043;
					nimln(13, "abc158_D.nim");
					LOC14 = 0;
					LOC14 = readline_15510(stdin);
					query = nsuSplitString(LOC14, ((NimStringDesc*) &TMP178));
					nimln(14, "abc158_D.nim");
					{
						if ((NU)(((NI) 0)) >= (NU)(query->Sup.len)) raiseIndexError();
						if (!eqStrings(query->data[((NI) 0)], ((NimStringDesc*) &TMP179))) goto LA17;
						nimln(15, "abc158_D.nim");
						lr = !(lr);
					}
					goto LA15;
					LA17: ;
					{
						nimln(17, "abc158_D.nim");
						{
							if (!lr) goto LA22;
							nimln(18, "abc158_D.nim");
							{
								if ((NU)(((NI) 1)) >= (NU)(query->Sup.len)) raiseIndexError();
								if (!eqStrings(query->data[((NI) 1)], ((NimStringDesc*) &TMP179))) goto LA26;
								nimln(19, "abc158_D.nim");
								if ((NU)(((NI) 2)) >= (NU)(query->Sup.len)) raiseIndexError();
								prepend_105244((&s_105039), query->data[((NI) 2)]);
							}
							goto LA24;
							LA26: ;
							{
								nimln(21, "abc158_D.nim");
								if ((NU)(((NI) 2)) >= (NU)(query->Sup.len)) raiseIndexError();
								append_105043((&s_105039), query->data[((NI) 2)]);
							}
							LA24: ;
						}
						goto LA20;
						LA22: ;
						{
							nimln(23, "abc158_D.nim");
							{
								if ((NU)(((NI) 1)) >= (NU)(query->Sup.len)) raiseIndexError();
								if (!eqStrings(query->data[((NI) 1)], ((NimStringDesc*) &TMP179))) goto LA32;
								nimln(24, "abc158_D.nim");
								if ((NU)(((NI) 2)) >= (NU)(query->Sup.len)) raiseIndexError();
								append_105043((&s_105039), query->data[((NI) 2)]);
							}
							goto LA30;
							LA32: ;
							{
								nimln(26, "abc158_D.nim");
								if ((NU)(((NI) 2)) >= (NU)(query->Sup.len)) raiseIndexError();
								prepend_105244((&s_105039), query->data[((NI) 2)]);
							}
							LA30: ;
						}
						LA20: ;
					}
					LA15: ;
					nimln(1895, "system.nim");
					TMP180 = addInt(res_106049, ((NI) 1));
					res_106049 = (NI)(TMP180);
				} LA13: ;
			}
		}
	}
	nimln(27, "abc158_D.nim");
	result_105003 = copyString(((NimStringDesc*) &TMP181));
	{
		NimStringDesc* i_105468;
		Doublylinkednodeobj105016* it_106056;
		i_105468 = 0;
		nimln(76, "lists.nim");
		it_106056 = s_105039.head;
		{
			nimln(77, "lists.nim");
			while (1) {
				nimln(349, "system.nim");
				if (!!((it_106056 == NIM_NIL))) goto LA37;
				nimln(78, "lists.nim");
				i_105468 = (*it_106056).value;
				nimln(29, "abc158_D.nim");
				result_105003 = resizeString(result_105003, i_105468->Sup.len + 0);
appendString(result_105003, i_105468);
				nimln(79, "lists.nim");
				it_106056 = (*it_106056).next;
			} LA37: ;
		}
	}
	nimln(30, "abc158_D.nim");
	{
		TY15805* result_105524;
		TY105477* s_105526;
		NI i_105528;
		TY15805* LOC49;
		if (!!(lr)) goto LA40;
		nimln(31, "abc158_D.nim");
		result_105524 = 0;
		nimln(595, "sequtils.nim");
		s_105526 = HEX40_105471(result_105003->data, result_105003->Sup.len);
		nimln(596, "sequtils.nim");
		i_105528 = ((NI) 0);
		nimln(597, "sequtils.nim");
		result_105524 = newseq_105810(((NI)chckRange((s_105526 ? s_105526->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		{
			NIM_CHAR it_105835;
			NI i_106062;
			NI L_106064;
			it_105835 = 0;
			nimln(3361, "system.nim");
			i_106062 = ((NI) 0);
			nimln(3362, "system.nim");
			L_106064 = (s_105526 ? s_105526->Sup.len : 0);
			{
				nimln(3363, "system.nim");
				while (1) {
					NI TMP183;
					NI TMP184;
					if (!(i_106062 < L_106064)) goto LA44;
					nimln(3364, "system.nim");
					if ((NU)(i_106062) >= (NU)(s_105526->Sup.len)) raiseIndexError();
					it_105835 = s_105526->data[i_106062];
					nimln(599, "sequtils.nim");
					if ((NU)(i_105528) >= (NU)(result_105524->Sup.len)) raiseIndexError();
					nimln(31, "abc158_D.nim");
					asgnRefNoCycle((void**) (&result_105524->data[i_105528]), nimCharToStr(it_105835));
					nimln(600, "sequtils.nim");
					TMP183 = addInt(i_105528, ((NI) 1));
					i_105528 = (NI)(TMP183);
					nimln(3365, "system.nim");
					TMP184 = addInt(i_106062, ((NI) 1));
					i_106062 = (NI)(TMP184);
					nimln(3366, "system.nim");
					{
						if (!!(((s_105526 ? s_105526->Sup.len : 0) == L_106064))) goto LA47;
						failedassertimpl_89116(((NimStringDesc*) &TMP185));
					}
					LA47: ;
				} LA44: ;
			}
		}
		LOC49 = 0;
		LOC49 = reversed_105848(result_105524->data, result_105524->Sup.len);
		result_105003 = nsuJoin(LOC49->data, LOC49->Sup.len);
	}
	LA40: ;
	nimln(32, "abc158_D.nim");
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result_105003;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_listsDatInit000();
	abc158_DDatInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_algorithmInit000();
	stdlib_listsInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	abc158_DInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, abc158_DInit000)(void) {
	NimStringDesc* LOC1;
	nimfr("abc158_D", "abc158_D.nim")
	nimln(35, "abc158_D.nim");
	LOC1 = 0;
	LOC1 = solve_105001();
	printf("%s\012", LOC1? (LOC1)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, abc158_DDatInit000)(void) {
}

