/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dotharaai/.choosenim/toolchains/nim-0.13.0/lib -o /home/dotharaai/projects/nim/abc158/nimcache/stdlib_lists.o /home/dotharaai/projects/nim/abc158/nimcache/stdlib_lists.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct Doublylinkedlist105010 Doublylinkedlist105010;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Doublylinkednodeobj105016 Doublylinkednodeobj105016;
typedef struct Cell47905 Cell47905;
typedef struct TNimType TNimType;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50214 Gcstat50214;
typedef struct TNimNode TNimNode;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Doublylinkednodeobj105016  {
Doublylinkednodeobj105016* next;
Doublylinkednodeobj105016* prev;
NimStringDesc* value;
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50214 stat;
};
struct  Doublylinkedlist105010  {
Doublylinkednodeobj105016* head;
Doublylinkednodeobj105016* tail;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, append_105069)(Doublylinkedlist105010* L, Doublylinkednodeobj105016* n);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47905*, usrtocell_51840)(void* usr);
static N_INLINE(void, rtladdzct_53401)(Cell47905* c);
N_NOINLINE(void, addzct_51817)(Cellseq47921* s, Cell47905* c);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(Doublylinkednodeobj105016*, newdoublylinkednode_105053)(NimStringDesc* value);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP154)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, prepend_105262)(Doublylinkedlist105010* L, Doublylinkednodeobj105016* n);
STRING_LITERAL(TMP152, "L.tail.next == nil ", 19);
STRING_LITERAL(TMP155, "L.head.prev == nil ", 19);
extern TFrame* frameptr_19436;
extern Gcheap50218 gch_50259;
TNimType NTI105016; /* DoublyLinkedNodeObj */
extern TNimType NTI138; /* string */
TNimType NTI105013; /* DoublyLinkedNode */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(void, initdoublylinkedlist_105005)(Doublylinkedlist105010* Result) {
	nimfr("initDoublyLinkedList", "lists.nim")
	popFrame();
}

static N_INLINE(Cell47905*, usrtocell_51840)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53401)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_51817((&gch_50259.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_51840(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_51840((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_53401(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, append_105069)(Doublylinkedlist105010* L, Doublylinkednodeobj105016* n) {
	nimfr("append", "lists.nim")
	nimln(236, "lists.nim");
	asgnRefNoCycle((void**) (&(*n).next), NIM_NIL);
	nimln(237, "lists.nim");
	asgnRefNoCycle((void**) (&(*n).prev), (*L).tail);
	nimln(238, "lists.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*L).tail == NIM_NIL))) goto LA3;
		nimln(239, "lists.nim");
		{
			if (!!(((*(*L).tail).next == NIM_NIL))) goto LA7;
			failedassertimpl_89116(((NimStringDesc*) &TMP152));
		}
		LA7: ;
		nimln(240, "lists.nim");
		asgnRefNoCycle((void**) (&(*(*L).tail).next), n);
	}
	LA3: ;
	nimln(241, "lists.nim");
	unsureAsgnRef((void**) (&(*L).tail), n);
	nimln(242, "lists.nim");
	{
		if (!((*L).head == NIM_NIL)) goto LA11;
		unsureAsgnRef((void**) (&(*L).head), n);
	}
	LA11: ;
	popFrame();
}
N_NIMCALL(void, TMP154)(void* p, NI op) {
	Doublylinkednodeobj105016* a;
	a = (Doublylinkednodeobj105016*)p;
	nimGCvisit((void*)(*a).next, op);
	nimGCvisit((void*)(*a).prev, op);
	nimGCvisit((void*)(*a).value, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47905* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_51840(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_53401(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Doublylinkednodeobj105016*, newdoublylinkednode_105053)(NimStringDesc* value) {
	Doublylinkednodeobj105016* result;
	NimStringDesc* LOC1;
	nimfr("newDoublyLinkedNode", "lists.nim")
	result = 0;
	nimln(67, "lists.nim");
	result = (Doublylinkednodeobj105016*) newObj((&NTI105013), sizeof(Doublylinkednodeobj105016));
	nimln(68, "lists.nim");
	LOC1 = 0;
	LOC1 = (*result).value; (*result).value = copyStringRC1(value);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, append_105043)(Doublylinkedlist105010* L, NimStringDesc* value) {
	Doublylinkednodeobj105016* LOC1;
	nimfr("append", "lists.nim")
	nimln(246, "lists.nim");
	LOC1 = 0;
	LOC1 = newdoublylinkednode_105053(value);
	append_105069(L, LOC1);
	popFrame();
}

N_NIMCALL(void, prepend_105262)(Doublylinkedlist105010* L, Doublylinkednodeobj105016* n) {
	nimfr("prepend", "lists.nim")
	nimln(250, "lists.nim");
	asgnRefNoCycle((void**) (&(*n).prev), NIM_NIL);
	nimln(251, "lists.nim");
	asgnRefNoCycle((void**) (&(*n).next), (*L).head);
	nimln(252, "lists.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*L).head == NIM_NIL))) goto LA3;
		nimln(253, "lists.nim");
		{
			if (!!(((*(*L).head).prev == NIM_NIL))) goto LA7;
			failedassertimpl_89116(((NimStringDesc*) &TMP155));
		}
		LA7: ;
		nimln(254, "lists.nim");
		asgnRefNoCycle((void**) (&(*(*L).head).prev), n);
	}
	LA3: ;
	nimln(255, "lists.nim");
	unsureAsgnRef((void**) (&(*L).head), n);
	nimln(256, "lists.nim");
	{
		if (!((*L).tail == NIM_NIL)) goto LA11;
		unsureAsgnRef((void**) (&(*L).tail), n);
	}
	LA11: ;
	popFrame();
}

N_NIMCALL(void, prepend_105244)(Doublylinkedlist105010* L, NimStringDesc* value) {
	Doublylinkednodeobj105016* LOC1;
	nimfr("prepend", "lists.nim")
	nimln(260, "lists.nim");
	LOC1 = 0;
	LOC1 = newdoublylinkednode_105053(value);
	prepend_105262(L, LOC1);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_listsInit000)(void) {
	nimfr("lists", "lists.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_listsDatInit000)(void) {
static TNimNode* TMP153[3];
static TNimNode TMP150[4];
NTI105016.size = sizeof(Doublylinkednodeobj105016);
NTI105016.kind = 18;
NTI105016.base = 0;
TMP153[0] = &TMP150[1];
TMP150[1].kind = 1;
TMP150[1].offset = offsetof(Doublylinkednodeobj105016, next);
TMP150[1].typ = (&NTI105013);
TMP150[1].name = "next";
TMP153[1] = &TMP150[2];
TMP150[2].kind = 1;
TMP150[2].offset = offsetof(Doublylinkednodeobj105016, prev);
TMP150[2].typ = (&NTI105013);
TMP150[2].name = "prev";
TMP153[2] = &TMP150[3];
TMP150[3].kind = 1;
TMP150[3].offset = offsetof(Doublylinkednodeobj105016, value);
TMP150[3].typ = (&NTI138);
TMP150[3].name = "value";
TMP150[0].len = 3; TMP150[0].kind = 2; TMP150[0].sons = &TMP153[0];
NTI105016.node = &TMP150[0];
NTI105013.size = sizeof(Doublylinkednodeobj105016*);
NTI105013.kind = 22;
NTI105013.base = (&NTI105016);
NTI105013.flags = 2;
NTI105013.marker = TMP154;
}

