/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dotharaai/.choosenim/toolchains/nim-0.13.0/lib -o /home/dotharaai/projects/nim/ABC169/nimcache/abc169_A.o /home/dotharaai/projects/nim/ABC169/nimcache/abc169_A.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY114006 TY114006;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47905 Cell47905;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(NimStringDesc*, ClPrc) (void* ClEnv);
void* ClEnv;
} TY114002;
struct  TY114006  {
NI HEX3Astate;
NimStringDesc* s114004;
NimStringDesc* HEX3Atmp114012;
NI last96798;
NI first97020;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50214 stat;
};
typedef N_CLOSURE_PTR(NimStringDesc*, TMP293) (void);
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP288)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_CLOSURE(NimStringDesc*, HEX3Aanonymous_114001)(void* ClEnv);
N_NIMCALL(NimStringDesc*, readline_15510)(FILE* f);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47905*, usrtocell_51840)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_53401)(Cell47905* c);
N_NOINLINE(void, addzct_51817)(Cellseq47921* s, Cell47905* c);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_80210, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_54219)(Cell47905* c);
static N_INLINE(NIM_BOOL, canbecycleroot_51858)(Cell47905* c);
static N_INLINE(void, rtladdcycleroot_52620)(Cell47905* c);
N_NOINLINE(void, incl_48647)(Cellset47917* s, Cell47905* cell);
static N_INLINE(void, decref_53801)(Cell47905* c);
N_NIMCALL(NI, read_114021)(void);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NI, solve_114024)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, abc169_AInit000)(void);
NIM_EXTERNC N_NOINLINE(void, abc169_ADatInit000)(void);
TY114002 get_114019;
TNimType NTI114006; /* object */
extern TNimType NTI104; /* int */
TNimType NTI114008; /* range -1..1(int) */
extern TNimType NTI138; /* string */
TNimType NTI114005; /* ref object */
extern TFrame* frameptr_19436;
extern Gcheap50218 gch_50259;
NI a_114029;
NI b_114030;
N_NIMCALL(void, TMP288)(void* p, NI op) {
	TY114006* a;
	a = (TY114006*)p;
	nimGCvisit((void*)(*a).s114004, op);
	nimGCvisit((void*)(*a).HEX3Atmp114012, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(Cell47905*, usrtocell_51840)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53401)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_51817((&gch_50259.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_51840(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_51840((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_53401(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_CLOSURE(NimStringDesc*, HEX3Aanonymous_114001)(void* ClEnv) {
	NimStringDesc* result;
	TY114006* HEX3Aenvp_114009;
	nimfr(":anonymous", "abc169_A.nim")
{	result = 0;
	HEX3Aenvp_114009 = (TY114006*) ClEnv;
	switch ((*HEX3Aenvp_114009).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	}
	STATE0: ;
	{
		nimln(4, "abc169_A.nim");
		asgnRefNoCycle((void**) (&(*HEX3Aenvp_114009).HEX3Atmp114012), readline_15510(stdin));
		nimln(371, "strutils.nim");
		(*HEX3Aenvp_114009).last96798 = ((NI) 0);
		{
			nimln(373, "strutils.nim");
			while (1) {
				if (!((*HEX3Aenvp_114009).last96798 < ((*HEX3Aenvp_114009).HEX3Atmp114012 ? (*HEX3Aenvp_114009).HEX3Atmp114012->Sup.len : 0))) goto LA3;
				{
					nimln(374, "strutils.nim");
					while (1) {
						NI TMP289;
						nimln(1098, "system.nim");
						if ((NU)((*HEX3Aenvp_114009).last96798) > (NU)((*HEX3Aenvp_114009).HEX3Atmp114012->Sup.len)) raiseIndexError();
						if (!(((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(32)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(9)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(11)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(13)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(10)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(12)))) goto LA5;
						nimln(374, "strutils.nim");
						TMP289 = addInt((*HEX3Aenvp_114009).last96798, ((NI) 1));
						(*HEX3Aenvp_114009).last96798 = (NI)(TMP289);
					} LA5: ;
				}
				nimln(375, "strutils.nim");
				(*HEX3Aenvp_114009).first97020 = (*HEX3Aenvp_114009).last96798;
				{
					nimln(376, "strutils.nim");
					while (1) {
						NIM_BOOL LOC8;
						NI TMP290;
						LOC8 = 0;
						LOC8 = ((*HEX3Aenvp_114009).last96798 < ((*HEX3Aenvp_114009).HEX3Atmp114012 ? (*HEX3Aenvp_114009).HEX3Atmp114012->Sup.len : 0));
						if (!(LOC8)) goto LA9;
						nimln(1104, "system.nim");
						if ((NU)((*HEX3Aenvp_114009).last96798) > (NU)((*HEX3Aenvp_114009).HEX3Atmp114012->Sup.len)) raiseIndexError();
						LOC8 = !((((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(32)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(9)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(11)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(13)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(10)) || ((NU8)((*HEX3Aenvp_114009).HEX3Atmp114012->data[(*HEX3Aenvp_114009).last96798])) == ((NU8)(12))));
						LA9: ;
						if (!LOC8) goto LA7;
						nimln(376, "strutils.nim");
						TMP290 = addInt((*HEX3Aenvp_114009).last96798, ((NI) 1));
						(*HEX3Aenvp_114009).last96798 = (NI)(TMP290);
					} LA7: ;
				}
				nimln(377, "strutils.nim");
				{
					NI TMP291;
					NI TMP292;
					TMP291 = subInt((*HEX3Aenvp_114009).last96798, ((NI) 1));
					if (!((*HEX3Aenvp_114009).first97020 <= (NI)(TMP291))) goto LA12;
					nimln(378, "strutils.nim");
					TMP292 = subInt((*HEX3Aenvp_114009).last96798, ((NI) 1));
					asgnRefNoCycle((void**) (&(*HEX3Aenvp_114009).s114004), copyStrLast((*HEX3Aenvp_114009).HEX3Atmp114012, (*HEX3Aenvp_114009).first97020, (NI)(TMP292)));
					nimln(4, "abc169_A.nim");
					(*HEX3Aenvp_114009).HEX3Astate = ((NI) 1);
					result = copyString((*HEX3Aenvp_114009).s114004);
					goto BeforeRet;
					STATE1: ;
				}
				LA12: ;
			} LA3: ;
		}
	}
	(*HEX3Aenvp_114009).HEX3Astate = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_51858)(Cell47905* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1U<<((NU)(((NU8) 1))&7U)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_52620)(Cell47905* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_48647((&gch_50259.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_54219)(Cell47905* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_51858(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_52620(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_53801)(Cell47905* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_53401(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_51858(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_52620(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell47905* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_51840(src);
		incref_54219(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell47905* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_51840((*dest));
		decref_53801(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, read_114021)(void) {
	NI result;
	NimStringDesc* LOC1;
	nimfr("read", "abc169_A.nim")
	result = 0;
	nimln(6, "abc169_A.nim");
	LOC1 = 0;
	LOC1 = get_114019.ClPrc(get_114019.ClEnv);
	result = nsuParseInt(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(NI, solve_114024)(NI a, NI b) {
	NI result;
	NI TMP294;
	nimfr("solve", "abc169_A.nim")
{	result = 0;
	nimln(9, "abc169_A.nim");
	TMP294 = mulInt(a, b);
	result = (NI)(TMP294);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	abc169_ADatInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_algorithmInit000();
	stdlib_sequtilsInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	abc169_AInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, abc169_AInit000)(void) {
	TY114006* HEX3Aanonymous_114020;
	TY114002 LOC1;
	NI LOC2;
	NimStringDesc* LOC3;
	nimfr("abc169_A", "abc169_A.nim")
	nimln(3, "abc169_A.nim");
	HEX3Aanonymous_114020 = 0;
	nimln(198, "system.nim");
	HEX3Aanonymous_114020 = (TY114006*) newObj((&NTI114005), sizeof(TY114006));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = HEX3Aanonymous_114001; LOC1.ClEnv = HEX3Aanonymous_114020;
	asgnRef((void**) (&get_114019.ClEnv), LOC1.ClEnv);
	get_114019.ClPrc = LOC1.ClPrc;
	nimln(12, "abc169_A.nim");
	a_114029 = read_114021();
	b_114030 = read_114021();
	nimln(14, "abc169_A.nim");
	LOC2 = 0;
	LOC2 = solve_114024(a_114029, b_114030);
	LOC3 = 0;
	LOC3 = nimIntToStr(LOC2);
	printf("%s\012", LOC3? (LOC3)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, abc169_ADatInit000)(void) {
static TNimNode* TMP287[5];
static TNimNode TMP138[6];
NTI114006.size = sizeof(TY114006);
NTI114006.kind = 18;
NTI114006.base = 0;
NTI114006.flags = 2;
TMP287[0] = &TMP138[1];
NTI114008.size = sizeof(NI);
NTI114008.kind = 20;
NTI114008.base = (&NTI104);
NTI114008.flags = 3;
TMP138[1].kind = 1;
TMP138[1].offset = offsetof(TY114006, HEX3Astate);
TMP138[1].typ = (&NTI114008);
TMP138[1].name = ":state";
TMP287[1] = &TMP138[2];
TMP138[2].kind = 1;
TMP138[2].offset = offsetof(TY114006, s114004);
TMP138[2].typ = (&NTI138);
TMP138[2].name = "s114004";
TMP287[2] = &TMP138[3];
TMP138[3].kind = 1;
TMP138[3].offset = offsetof(TY114006, HEX3Atmp114012);
TMP138[3].typ = (&NTI138);
TMP138[3].name = ":tmp114012";
TMP287[3] = &TMP138[4];
TMP138[4].kind = 1;
TMP138[4].offset = offsetof(TY114006, last96798);
TMP138[4].typ = (&NTI104);
TMP138[4].name = "last96798";
TMP287[4] = &TMP138[5];
TMP138[5].kind = 1;
TMP138[5].offset = offsetof(TY114006, first97020);
TMP138[5].typ = (&NTI104);
TMP138[5].name = "first97020";
TMP138[0].len = 5; TMP138[0].kind = 2; TMP138[0].sons = &TMP287[0];
NTI114006.node = &TMP138[0];
NTI114005.size = sizeof(TY114006*);
NTI114005.kind = 22;
NTI114005.base = (&NTI114006);
NTI114005.flags = 2;
NTI114005.marker = TMP288;
}

